//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apply_file
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string file_path { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual users users { get; set; }
    }
}
