//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orgs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orgs()
        {
            this.users = new HashSet<users>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string org_no { get; set; }
        public Nullable<System.DateTimeOffset> created_at { get; set; }
        public Nullable<System.DateTimeOffset> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users> users { get; set; }
    }
}
