//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.apply_file = new HashSet<apply_file>();
        }
    
        public int id { get; set; }
        public Nullable<int> user_type { get; set; }
        public Nullable<int> org_id { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string email { get; set; }
        public string user_account { get; set; }
        public string user_hash { get; set; }
        public string user_salt { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTimeOffset> created_at { get; set; }
        public Nullable<System.DateTimeOffset> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apply_file> apply_file { get; set; }
        public virtual orgs orgs { get; set; }
    }
}
